### ISSUE TITLE
The repo is showing a different license, is that normal?

### ISSUE THREAD

**Issue by cjdcordeiro** [ubuntu-rocks/chiselled-jre#12]
https://github.com/ubuntu-rocks/chiselled-jre/blob/438e83de279ac312e8f3b62fe25f51b1b793649f/LICENSE#L3

**Comment by valentincanonical** [comment]
I see https://github.com/ubuntu-rocks/chiselled-jre/blob/main/LICENSE is still the GPLv3 (as shown on the repo).
I'm quite confused as the PR #1 is shown as merged into `main`, but `main` currently shows the same state as 3 days ago and still showing the GPLv3 LICENSE file (as the only file there).

In any case, https://github.com/ubuntu-rocks/chiselled-jre/blob/channels/8/edge/LICENSE also seems to be interpreted by GitHub as "GPLv3". I don't know whether this is a side effect of the main branch determining what is the License for the entire project... or whether this is another issue.
